wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1677175900.17205
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.8
      5: 0.13.10
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 32
hidden_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
max_episodes:
  desc: null
  value: 501
